// 仪表盘统计数据
export const dashboardStats = [
  {
    id: 'total-products',
    title: '产品总数',
    value: '1,247',
    change: '+12',
    changeType: 'increase', // increase | decrease | neutral
    description: '较上月增长',
    iconColor: 'bg-slate-600',
  },
  {
    id: 'total-inventory',
    title: '库存总量',
    value: '8,924',
    change: '-156',
    changeType: 'decrease',
    description: '较上周减少',
    iconColor: 'bg-slate-600',
  },
  {
    id: 'low-stock-alerts',
    title: '低库存预警',
    value: '23',
    change: '+5',
    changeType: 'increase',
    description: '需及时补货',
    iconColor: 'bg-amber-500',
  },
  {
    id: 'today-transactions',
    title: '今日出入库',
    value: '48',
    change: '+8',
    changeType: 'increase',
    description: '较昨日增加',
    iconColor: 'bg-slate-600',
  },
];

// 最近出入库记录
export const recentTransactions = [
  {
    id: 'txn-001',
    productName: '离心管 50mL',
    type: '出库',
    quantity: 120,
    date: '2026-03-29 14:30',
    operator: '张三',
    status: 'completed',
  },
  {
    id: 'txn-002',
    productName: '移液器吸头',
    type: '入库',
    quantity: 500,
    date: '2026-03-29 11:15',
    operator: '李四',
    status: 'completed',
  },
  {
    id: 'txn-003',
    productName: 'PCR 板',
    type: '出库',
    quantity: 25,
    date: '2026-03-28 16:45',
    operator: '王五',
    status: 'completed',
  },
  {
    id: 'txn-004',
    productName: '细胞培养瓶',
    type: '入库',
    quantity: 80,
    date: '2026-03-28 09:20',
    operator: '赵六',
    status: 'pending',
  },
  {
    id: 'txn-005',
    productName: '冻存管',
    type: '出库',
    quantity: 60,
    date: '2026-03-27 13:10',
    operator: '钱七',
    status: 'completed',
  },
];

// 低库存预警概览
export const stockAlerts = [
  {
    id: 'alert-001',
    productName: '酶标板',
    currentStock: 12,
    minStock: 50,
    category: '耗材',
    urgency: 'high', // high | medium | low
  },
  {
    id: 'alert-002',
    productName: '血清',
    currentStock: 8,
    minStock: 20,
    category: '试剂',
    urgency: 'high',
  },
  {
    id: 'alert-003',
    productName: '离心管 15mL',
    currentStock: 45,
    minStock: 100,
    category: '耗材',
    urgency: 'medium',
  },
  {
    id: 'alert-004',
    productName: '细胞培养基',
    currentStock: 32,
    minStock: 50,
    category: '试剂',
    urgency: 'medium',
  },
  {
    id: 'alert-005',
    productName: '冻存盒',
    currentStock: 28,
    minStock: 40,
    category: '设备',
    urgency: 'low',
  },
  {
    id: 'alert-006',
    productName: 'PCR 板 (96孔)',
    currentStock: 18,
    minStock: 30,
    category: '耗材',
    urgency: 'high',
  },
  {
    id: 'alert-007',
    productName: '离心管 50mL',
    currentStock: 22,
    minStock: 50,
    category: '耗材',
    urgency: 'high',
  },
  {
    id: 'alert-008',
    productName: '冻存管 (2mL)',
    currentStock: 65,
    minStock: 100,
    category: '耗材',
    urgency: 'medium',
  },
  {
    id: 'alert-009',
    productName: '移液器吸头 (10µL)',
    currentStock: 85,
    minStock: 200,
    category: '耗材',
    urgency: 'low',
  },
  {
    id: 'alert-010',
    productName: '细胞培养瓶 (25cm²)',
    currentStock: 15,
    minStock: 40,
    category: '耗材',
    urgency: 'high',
  },
];

// 产品列表数据
export const products = [
  {
    id: 'prod-001',
    sku: 'PRD-2026001',
    name: '离心管 50mL',
    category: '耗材',
    currentStock: 125,
    minStock: 50,
    unit: '个',
    location: 'A区-3排-2层',
    status: '正常',
    lastUpdated: '2026-03-28',
  },
  {
    id: 'prod-002',
    sku: 'PRD-2026002',
    name: '移液器吸头 (10µL)',
    category: '耗材',
    currentStock: 520,
    minStock: 200,
    unit: '盒',
    location: 'B区-1排-4层',
    status: '正常',
    lastUpdated: '2026-03-29',
  },
  {
    id: 'prod-003',
    sku: 'PRD-2026003',
    name: 'PCR 板 (96孔)',
    category: '耗材',
    currentStock: 35,
    minStock: 30,
    unit: '个',
    location: 'A区-2排-1层',
    status: '低库存',
    lastUpdated: '2026-03-27',
  },
  {
    id: 'prod-004',
    sku: 'PRD-2026004',
    name: '细胞培养瓶 (25cm²)',
    category: '耗材',
    currentStock: 80,
    minStock: 40,
    unit: '个',
    location: 'C区-4排-3层',
    status: '正常',
    lastUpdated: '2026-03-28',
  },
  {
    id: 'prod-005',
    sku: 'PRD-2026005',
    name: '血清 (胎牛)',
    category: '试剂',
    currentStock: 15,
    minStock: 20,
    unit: '瓶',
    location: '冷藏室-2层',
    status: '低库存',
    lastUpdated: '2026-03-26',
  },
  {
    id: 'prod-006',
    sku: 'PRD-2026006',
    name: '酶标板',
    category: '耗材',
    currentStock: 22,
    minStock: 50,
    unit: '个',
    location: 'A区-1排-2层',
    status: '低库存',
    lastUpdated: '2026-03-25',
  },
  {
    id: 'prod-007',
    sku: 'PRD-2026007',
    name: '冻存管 (2mL)',
    category: '耗材',
    currentStock: 180,
    minStock: 100,
    unit: '包',
    location: 'B区-3排-1层',
    status: '正常',
    lastUpdated: '2026-03-29',
  },
  {
    id: 'prod-008',
    sku: 'PRD-2026008',
    name: '细胞培养基 (DMEM)',
    category: '试剂',
    currentStock: 42,
    minStock: 50,
    unit: '瓶',
    location: '冷藏室-3层',
    status: '低库存',
    lastUpdated: '2026-03-28',
  },
  {
    id: 'prod-009',
    sku: 'PRD-2026009',
    name: '离心管 15mL',
    category: '耗材',
    currentStock: 95,
    minStock: 100,
    unit: '个',
    location: 'A区-3排-3层',
    status: '低库存',
    lastUpdated: '2026-03-27',
  },
  {
    id: 'prod-010',
    sku: 'PRD-2026010',
    name: '冻存盒 (9格)',
    category: '设备',
    currentStock: 28,
    minStock: 40,
    unit: '个',
    location: 'D区-2排-2层',
    status: '低库存',
    lastUpdated: '2026-03-26',
  },
  {
    id: 'prod-011',
    sku: 'PRD-2026011',
    name: '移液器吸头 (200µL)',
    category: '耗材',
    currentStock: 320,
    minStock: 150,
    unit: '盒',
    location: 'B区-2排-4层',
    status: '正常',
    lastUpdated: '2026-03-29',
  },
  {
    id: 'prod-012',
    sku: 'PRD-2026012',
    name: 'PCR 板 (384孔)',
    category: '耗材',
    currentStock: 18,
    minStock: 25,
    unit: '个',
    location: 'A区-2排-2层',
    status: '低库存',
    lastUpdated: '2026-03-28',
  },
];

// 出入库记录数据
export const transactionRecords = [
  {
    id: 'txn-001',
    productName: '离心管 50mL',
    type: '出库',
    quantity: 120,
    unit: '个',
    date: '2026-03-29 14:30',
    operator: '张三',
    status: 'completed',
    notes: '实验室日常使用',
  },
  {
    id: 'txn-002',
    productName: '移液器吸头 (10µL)',
    type: '入库',
    quantity: 500,
    unit: '盒',
    date: '2026-03-29 11:15',
    operator: '李四',
    status: 'completed',
    notes: '新采购批次',
  },
  {
    id: 'txn-003',
    productName: 'PCR 板 (96孔)',
    type: '出库',
    quantity: 25,
    unit: '个',
    date: '2026-03-29 09:45',
    operator: '王五',
    status: 'completed',
    notes: '实验项目领用',
  },
  {
    id: 'txn-004',
    productName: '细胞培养瓶 (25cm²)',
    type: '入库',
    quantity: 80,
    unit: '个',
    date: '2026-03-28 16:20',
    operator: '赵六',
    status: 'pending',
    notes: '待质检',
  },
  {
    id: 'txn-005',
    productName: '血清 (胎牛)',
    type: '出库',
    quantity: 8,
    unit: '瓶',
    date: '2026-03-28 14:10',
    operator: '钱七',
    status: 'completed',
    notes: '细胞培养使用',
  },
  {
    id: 'txn-006',
    productName: '酶标板',
    type: '入库',
    quantity: 50,
    unit: '个',
    date: '2026-03-28 10:30',
    operator: '张三',
    status: 'completed',
    notes: '',
  },
  {
    id: 'txn-007',
    productName: '冻存管 (2mL)',
    type: '出库',
    quantity: 60,
    unit: '包',
    date: '2026-03-27 15:40',
    operator: '李四',
    status: 'completed',
    notes: '样本保存',
  },
  {
    id: 'txn-008',
    productName: '细胞培养基 (DMEM)',
    type: '入库',
    quantity: 30,
    unit: '瓶',
    date: '2026-03-27 13:25',
    operator: '王五',
    status: 'completed',
    notes: '新批次到货',
  },
  {
    id: 'txn-009',
    productName: '离心管 15mL',
    type: '出库',
    quantity: 45,
    unit: '个',
    date: '2026-03-26 11:55',
    operator: '赵六',
    status: 'completed',
    notes: '',
  },
  {
    id: 'txn-010',
    productName: '冻存盒 (9格)',
    type: '入库',
    quantity: 20,
    unit: '个',
    date: '2026-03-26 09:10',
    operator: '钱七',
    status: 'completed',
    notes: '设备补充',
  },
  {
    id: 'txn-011',
    productName: '移液器吸头 (200µL)',
    type: '出库',
    quantity: 150,
    unit: '盒',
    date: '2026-03-25 16:30',
    operator: '张三',
    status: 'completed',
    notes: '实验室日常消耗',
  },
  {
    id: 'txn-012',
    productName: 'PCR 板 (384孔)',
    type: '入库',
    quantity: 40,
    unit: '个',
    date: '2026-03-25 14:20',
    operator: '李四',
    status: 'completed',
    notes: '新规格采购',
  },
  {
    id: 'txn-013',
    productName: '离心管 50mL',
    type: '入库',
    quantity: 200,
    unit: '个',
    date: '2026-03-24 10:45',
    operator: '王五',
    status: 'completed',
    notes: '',
  },
  {
    id: 'txn-014',
    productName: '血清 (胎牛)',
    type: '出库',
    quantity: 5,
    unit: '瓶',
    date: '2026-03-24 09:15',
    operator: '赵六',
    status: 'completed',
    notes: '实验使用',
  },
  {
    id: 'txn-015',
    productName: '酶标板',
    type: '出库',
    quantity: 15,
    unit: '个',
    date: '2026-03-23 15:30',
    operator: '钱七',
    status: 'completed',
    notes: '项目领用',
  },
  {
    id: 'txn-016',
    productName: '冻存管 (2mL)',
    type: '入库',
    quantity: 100,
    unit: '包',
    date: '2026-03-23 11:20',
    operator: '张三',
    status: 'completed',
    notes: '补货',
  },
  {
    id: 'txn-017',
    productName: '细胞培养基 (DMEM)',
    type: '出库',
    quantity: 12,
    unit: '瓶',
    date: '2026-03-22 14:50',
    operator: '李四',
    status: 'completed',
    notes: '',
  },
  {
    id: 'txn-018',
    productName: '离心管 15mL',
    type: '入库',
    quantity: 80,
    unit: '个',
    date: '2026-03-22 10:10',
    operator: '王五',
    status: 'completed',
    notes: '新采购',
  },
  {
    id: 'txn-019',
    productName: '冻存盒 (9格)',
    type: '出库',
    quantity: 8,
    unit: '个',
    date: '2026-03-21 16:05',
    operator: '赵六',
    status: 'completed',
    notes: '实验室配置',
  },
  {
    id: 'txn-020',
    productName: '移液器吸头 (10µL)',
    type: '出库',
    quantity: 200,
    unit: '盒',
    date: '2026-03-21 13:40',
    operator: '钱七',
    status: 'completed',
    notes: '日常消耗',
  },
];